modLoader = "javafml"
loaderVersion = "[44,)"
license = "CC BY-NC-ND 4.0"
showAsResourcePack = false

[[mods]]
modId = "crop_marker"
version = "1.19.4-1.2.0"
displayName = "FullGrownCropMarker"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/full-grown-crop-marker"
#logoFile="examplemod.png"
#credits=""
authors = "Buecher_wurm"
description = '''Adds a little marker over all crops that are at their maximum age!'''
displayTest = "IGNORE_ALL_VERSION" #client only mod

[[dependencies.crop_marker]]
modId = "forge"
mandatory = true
versionRange = "[44.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crop_marker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
